#!/usr/bin/env bash
# manages manage_my_process

handle_start() {
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
	echo "manage_my_process started"
}

handle_stop() {
	if [ -f /var/run/my_process.pid ];
	then
		pid=$(cat /var/run/my_process.pid)
        	kill -2 "$pid"
		echo "manage_my_process stopped"
        	rm  -r /var/run/my_process.pid
	fi
}

handle_restart() {
        if [ -f /var/run/my_process.pid ];
	then
		pid=$(cat /var/run/my_process.pid)
		kill -2 "$pid"
		rm  -r /var/run/my_process.pid
	fi
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
        echo "manage_my_process restarted"
}

if  [ "$1" == "start" ];
then
	handle_start
elif [ "$1" == "stop" ];
then
	handle_stop
elif [ "$1" == "restart" ];
then
	handle_restart
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
