#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code from the Apache log file.

log_file="apache-access.log"
if [ -f "$log_file" ] && [ -s "$log_file" ];
then
	var=$(awk 'NF>1 && NF>=9 {ip_status[$1" "$9]++} END {for (key in ip_status) {print ip_status[key], key}}' "$log_file" | sort -nr)

	echo "$var"
fi
