#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59
i=0
y=1
while ((i <= 12));
do
	echo "Hour: $i"

	while ((y <= 59));
	do
		echo "$y"
		((y++))
	done

	y=1
	((i++))

done
