#!/usr/bin/env bash
# Write a Bash script that displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

i=0
for i in *;
do
	if [[ "$i" == .* ]];
	then
		continue;
	fi

	remove_dash="${i#*-}"

	echo "$remove_dash"
done
